<?php

/*
 * This file is part of the symfony package.
 * (c) 2004, 2005 Fabien Potencier <fabien.potencier@symfony-project.com>
 * (c) 2004, 2005 Sean Kerr.
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Pre-initialization script.
 *
 * @package    symfony
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @author     Sean Kerr <skerr@mojavi.org>
 * @version    SVN: $Id$
 */

/**
 * Handles autoloading of classes that have been specified in autoload.yml and myautoload.yml.
 *
 * @param string A class name.
 *
 * @return void
 */
function __autoload($class)
{
  // this static variable is generated by the $config file below
  static $classes;

  if (!isset($classes))
  {
    try
    {
      // include the list of autoload classes
      $config = sfConfigCache::checkConfig(sfConfig::getInstance()->get('sf_app_config_dir_name').'/autoload.yml');
    }
    catch (sfException $e)
    {
      $e->printStackTrace();
    }
    catch (Exception $e)
    {
      // unknown exception
      $e = new sfException($e->getMessage());

      $e->printStackTrace();
    }

    require_once($config);
  }

  if (!isset($classes[$class]))
  {
    // unspecified class
    $error = 'Autoloading of class "%s" failed';
    $error = sprintf($error, $class);
    $e = new sfAutoloadException($error);

    $e->printStackTrace();
  }

  // class exists, let's include it
  require_once($classes[$class]);
}

try
{
  ini_set('unserialize_callback_func', '__autoload');

  // symfony version information
/*
  define('SF_APP_NAME',          'symfony');
  define('SF_APP_MAJOR_VERSION', '1');
  define('SF_APP_MINOR_VERSION', '0');
  define('SF_APP_MICRO_VERSION', '0');
  define('SF_APP_BRANCH',        'dev-1.0.0');
  define('SF_APP_STATUS',        'DEV');
  define('SF_APP_VERSION',       SF_APP_MAJOR_VERSION.'.'.
                                 SF_APP_MINOR_VERSION.'.'.
                                 SF_APP_MICRO_VERSION.'-'.SF_APP_STATUS);
  define('SF_APP_URL',           'http://www.symfony-project.com/');
  define('SF_APP_INFO',          SF_APP_NAME.' '.SF_APP_VERSION.' ('.SF_APP_URL.')');
*/

  // get config instance
  $config = sfConfig::getInstance();
  $sf_app_config_dir_name = $config->get('sf_app_config_dir_name');

  if (!$config->get('sf_in_bootstrap'))
  {
    // YAML support
    require_once('spyc/spyc.php');
    require_once('symfony/util/sfYaml.class.php');

    // cache support
    require_once('symfony/cache/sfCache.class.php');
    require_once('symfony/cache/sfFileCache.class.php');

    // config support
    require_once('symfony/config/sfConfigCache.class.php');
    require_once('symfony/config/sfConfigHandler.class.php');
    require_once('symfony/config/sfYamlConfigHandler.class.php');
    require_once('symfony/config/sfAutoloadConfigHandler.class.php');
    require_once('symfony/config/sfRootConfigHandler.class.php');

    // basic exception classes
    require_once('symfony/exception/sfException.class.php');
    require_once('symfony/exception/sfAutoloadException.class.php');
    require_once('symfony/exception/sfCacheException.class.php');
    require_once('symfony/exception/sfConfigurationException.class.php');
    require_once('symfony/exception/sfParseException.class.php');

    // utils
    require_once('symfony/util/sfParameterHolder.class.php');

    // create bootstrap file for next time
    if (!$config->get('sf_debug') && !$config->get('sf_test'))
    {
      sfConfigCache::checkConfig($sf_app_config_dir_name.'/bootstrap_compile.yml');
    }
  }

  // set exception format
  sfException::setFormat(isset($_SERVER['HTTP_HOST']) ? 'html' : 'plain');

  if ($config->get('sf_debug'))
  {
    // clear our config and module cache
    sfConfigCache::clear();
  }

  // load base settings
  include(sfConfigCache::checkConfig($sf_app_config_dir_name.'/logging.yml'));
  sfConfigCache::import($sf_app_config_dir_name.'/php.yml');
  include(sfConfigCache::checkConfig($sf_app_config_dir_name.'/settings.yml'));
  include(sfConfigCache::checkConfig($sf_app_config_dir_name.'/app.yml'));

  // error settings
  ini_set('display_errors', $config->get('sf_debug') ? 'on' : 'off');
  error_reporting($config->get('sf_error_reporting'));

  // compress output
  ob_start($config->get('sf_compressed') ? 'ob_gzhandler' : '');

/*
  if ($config->get('sf_logging_active'))
  {
    set_error_handler(array('sfLogger', 'errorHandler'));
  }
*/

  // required core classes for the framework
  // we create a temp var to avoid substitution during compilation
  if (!$config->get('sf_debug') && !$config->get('sf_test'))
  {
    $core_classes = $sf_app_config_dir_name.'/core_compile.yml';
    sfConfigCache::import($core_classes);
  }

  if ($config->get('sf_routing'))
  {
    sfConfigCache::import($sf_app_config_dir_name.'/routing.yml');
  }
}
catch (sfException $e)
{
  $e->printStackTrace();
}
catch (Exception $e)
{
  // unknown exception
  $e = new sfException($e->getMessage());

  $e->printStackTrace();
}

?>